language: rust
sudo: false

rust:
  - stable
  - beta

jobs:
  include:
    - stage: deploy
      rust: stable
      script: skip
      deploy:
        - provider: cargo
          token:
            secure: Aa0jA4xXa8Bai6M1pO2dsujPM/DVHLHHkczx0eSO7ZiP0zKaaDbCrvy3tzTTStm6AI4NtIU69xIWg4j2JPnqxgHn0ZeYSZDGbe6UjjfzSQmTRqc56zoP3hFcdjVGNqaYE0RNJWxSvzEryE47HLKU51OGJkY1AWJuGG3tQM+mBM0AkPIEl/AlgGBvE+nAqOH7jE3rEsfqPoVrRzgTAuAVp6kOSHL36eGXxcKSIG/TsnQjUFmNxvSVHMizPGFUagjfDWMdW9bwds5Cr2gkvEOJpALEqZ/eg0+sdHosqL0mB/R0WQ7wLkPDe7xS8GBHhIh8GESzbNoN5FGBCpVzMWxgEMtDeBPLEQ9hX4YLfJkb4MueT1G09/yQR6o3XTgft/TumE/b8rXBSsniSMPjpHI+XOKZlQo1GK6G9GR37+ziizR8ltSBsop/sltB79e8UN1HJpgXWK8D5dX4dX/LVjDl3AS8kwI3O0dbWk/B/ZS+QInQc1lUjrsNTMU9tVaZlaZZmEp1obG6s7yeK8LGg1WFvFevSVyz6LhUqMBGV2Gvi++AUvqRMWmPSe3rcUoCziQ4SMHJOpZUFCjbjvZYc08erMl1Z6n+1Hg/Oiuhj/iabjOS/ZT/ZAr5QKIap7VDMpXF2dQANLyGVrtFL93IZ3XPA6VXq8j11U1Xx6y/GeTU5As=
          on:
            repo: odarbelaeze/vegas-lattice-rs
            branch: master
            tags: true
