[package]
name = "vegas-lattice"
version = "0.1.0"
authors = ["Oscar David Arbeláez Echeverri <odarbelaeze@gmail.com>"]

[dependencies]
serde_json = "1.0"
serde = "*"
serde_derive = "*"
itertools = "0.6.0"
sprs = "*"

[dependencies.clap]
version = "~2.19.0"
features = [ "yaml" ]